; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define MyAppName "Multi-Display VCP Server"
#define MyAppVersion "2.0.0"
#define MyAppPublisher "DoggoDogPack"
#define MyAppURL "https://github.com/doggdogpack/MultiDisplayVCPServer"
#define MyAppExeName "MultiDisplayVCPServer.exe"
#define MyAppAssocName MyAppName + ""
#define MyAppAssocExt ".exe"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
AppId={{0583E799-3B68-42A8-BB3E-EF55F30F9EA1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={code:GetDefaultDir}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=E:\Projects\MultiDisplayVCP\Source\Server\LICENSE.txt
PrivilegesRequired=lowest 
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=E:\Projects\MultiDisplayVCP\BuildOut\Server\Packaged
OutputBaseFilename=MultiDisplayVCPServer_Windows_v2.0.0_Setup
SetupIconFile=E:\Projects\MultiDisplayVCP\Source\Server\monitor.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "E:\Projects\MultiDisplayVCP\BuildOut\Server\Output\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion restartreplace
Source: "E:\Projects\MultiDisplayVCP\BuildOut\Server\Output\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Registry]
Root: HKCU; Subkey: "Software\{#MyAppPublisher}\{#MyAppName}"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "MultiDisplayVCPServer"; Flags: uninsdeletevalue

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
; 1. Terminate the running application using the Windows taskkill command
Filename: "taskkill.exe"; Parameters: "/F /IM {#MyAppExeName}"; Flags: runhidden; StatusMsg: "Closing running instances of {#MyAppName}..."

[Code]
var
  // Flag to ensure the prompt only runs once
  PromptExecuted: Boolean;
  // Global flag to track if the user wants to delete data
  UserWantsToDeleteData: Boolean;

function GetDefaultDir(Param: String): String;
begin
  if IsAdminInstallMode then
  begin
    // All Users (Admin) Install: Use 64-bit Program Files
    Result := ExpandConstant('{pf}\{#MyAppName}');
  end
  else
  begin
    // Per-User Install: Use AppData\Local
    Result := ExpandConstant('{localappdata}\{#MyAppName}');
  end;
end;

// This procedure runs when the uninstall step changes
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  UserDataChoice: Integer;
  FindRec: TFindRec;
  DataPath: string;
  UserDataDir: string;
begin
  if (CurUninstallStep = usUninstall) and (not PromptExecuted) then
  begin
    PromptExecuted := True; // Set flag to prevent repeat execution
    UserWantsToDeleteData := False; // Default to false

    UserDataChoice := MsgBox('Do you want to permanently delete all user data and settings for {#MyAppName}? This includes saved passwords and port configurations.',
                             mbConfirmation, mb_YesNo);
    
    if UserDataChoice = idYes then
    begin
      UserWantsToDeleteData := True; // Set global flag

      UserDataDir := ExpandConstant('{localappdata}\{#MyAppName}');

      // 1. Delete all user data files/folders
      if FindFirst(UserDataDir + '\{#MyAppName}_Url_*', FindRec) then
      begin
        try
          repeat
            DataPath := UserDataDir + '\' + FindRec.Name;
            if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0 then
            begin
              DelTree(DataPath, True, True, True); // Delete sub-directory
            end
            else
            begin
              DeleteFile(DataPath); // Delete file
            end;

          until not FindNext(FindRec);
        finally
          FindClose(FindRec);
        end;
      end;
      
      // 2. Delete other known remnant files from the data folder
      DeleteFile(UserDataDir + '\desktop.ini');
    end;
  end;
end;

// This procedure runs *after* the uninstallation is complete
procedure DeInitializeUninstall();
var
  UserDataDir: string;
begin
  if UserWantsToDeleteData then
  begin
    RemoveDir(ExpandConstant('{app}'));
    UserDataDir := ExpandConstant('{localappdata}\{#MyAppName}');
    RemoveDir(UserDataDir);
  end;
end;